version: '3.8'

services:
  recipesdb:
    image: mysql:8.0
    container_name: recipesdb_container
    ports:
      - 3306:3306
    restart: always
    env_file:
      - ./db/env/db.env
    volumes:
      - recipesdb:/var/lib/mysql
    networks:
      - recipes_network

  recipesapache:
    build: ./
    container_name: recipesapache_container
    ports:
      - 80:80
    restart: always
    volumes:
      - ./:/var/www/html
    networks:
      - recipes_network

volumes:
  recipesdb: {}

networks:
  recipes_network:
    driver: bridge
