version: '3.8'

services:
  recipesdb:
    image: mysql:8.0
    container_name: recipesdb_container
    ports:
      - 3306:3306
    restart: always
    env_file:
      - ./db/env/db.env
    volumes:
      - ./db/scripts/admin.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/scripts/users.sql:/docker-entrypoint-initdb.d/2.sql
      - ./db/scripts/categories.sql:/docker-entrypoint-initdb.d/3.sql
      - ./db/scripts/recipes.sql:/docker-entrypoint-initdb.d/4.sql
      - ./db/scripts/rates.sql:/docker-entrypoint-initdb.d/5.sql
      - ./db/scripts/comments.sql:/docker-entrypoint-initdb.d/6.sql
      - recipesdb:/var/lib/mysql
    networks:
      - recipes_network

  recipesapache:
    build: ./
    container_name: recipesapache_container
    ports:
      - 80:80
    restart: always
    volumes:
      - ./src:/var/www/html
    networks:
      - recipes_network

volumes:
  recipesdb: {}

networks:
  recipes_network:
    driver: bridge
